---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grott
  namespace: growatt
  labels:
    app: grott
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grott
  template:
    metadata:
      labels:
        app: grott
    spec:
      containers:
      - name: grott
        image: ledidobe/grott:2.7.8
        ports:
        - containerPort: 5278
          hostPort: 5279

