---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: growatt
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 9000
          hostPort: 9001
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
          items:
          - key: mosquitto.conf
            path: mosquitto.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: growatt
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9000
